#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
userresources=$HOME/config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge Xresources - System
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

# Modify Xmodmap/Keyboard Layout - System
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

# Merge Xresources - User
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# Modify Xmodmap/Keyboard Layout - User
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Move location of xsession errors
if [ -f $HOME/.xsession-err?* ]; then
    for f in $HOME/.xsession-err?* ; do
        mv "$f" /home/duclos/.config/X11/xsession-error
    done
    unset f
fi

# WM
exec herbstluftwm -l
