#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Move location of xsession errors
if [ -f $HOME/.xsession-err?* ]; then
    for f in $HOME/.xsession-err?* ; do
        mv "$f" /home/duclos/.config/X11/xsession-error
    done
    unset f
fi

# WM
picom -c -b
nitrogen --restore &
sxhkd &
dunst &

exec bspwm

