#!/bin/bash
#______  ___________ _    ____  ___
#| ___ \/  ___| ___ \ |  | |  \/  |
#| |_/ /\ `--.| |_/ / |  | | .  . |
#| ___ \ `--. \  __/| |/\| | |\/| |
#| |_/ //\__/ / |   \  /\  / |  | |
#\____/ \____/\_|    \/  \/\_|  |_/
#                                  

# ----------
# -- Prep --
# ----------
[ -f ~/.scripts/tlbx/tlbx_monitors_functions.sh ] \
&& source ~/.scripts/tlbx/tlbx_monitors_functions.sh

# ---------------
# -- Variables --
# ---------------
zero=0
positive_gap=5
negative_gap=-$positive_gap
panel_height=35

export zero
export gap
export positive_gap
export negative_gap
export panel_height
export upper_extra_gap

# ------------
# -- Colors --
# ------------
bspc config focused_border_color "#00bcd4"
bspc config active_border_color "#263238"
bspc config normal_border_color "#263238"
bspc config presel_feedback_color "#ffffff"
bspc config border_width 2

# ----------
# -- Gaps --
# ----------
bspc config window_gap $positive_gap
bspc config top_padding $(($panel_height+$positive_gap))
bspc config left_padding $positive_gap
bspc config right_padding $positive_gap
bspc config bottom_padding $positive_gap

# -------------
# -- Windows --
# -------------
bspc config automatic_scheme    alternate
bspc config split_ratio         0.55
bspc config honor_size_hints    false

# -------------
# -- Monocle --
# -------------
bspc config gapless_monocle     false 
bspc config borderless_monocle  false
bspc config single_monocle true

# -----------------------
# -- Monitors/Desktops --
# -----------------------
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

if [ $(monitors::count_monitors) -lt 2 ]; then
    ~/.config/polybar/launch.bash

    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    bspc desktop -f 4
else
    monitor_configuration
fi

bspc config pointer_follows_monitor true

bspc desktop 1 --layout monocle
bspc desktop 3 --layout monocle
bspc desktop 6 --layout monocle

# -------------
# -- Pointer --
# -------------
bspc config focus_follows_pointer false

# -----------
# -- Rules --
# -----------
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Zathura state=tiled 
bspc rule -a Pcmanfm state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a Polybar state=floating 
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Zoom state=tiled
bspc rule -a scratchterm sticky=on state=floating hidden=on locked=on

# xprop | grep WM_CLASS # finds window class
# xdo -n $NAME          # searches for window with instance name $NAME
# xdo id -N $CLASS      # searches for window with class $CLASS
