#______ _____ _____ ________  ___
#| ___ \_   _/  __ \  _  |  \/  |
#| |_/ / | | | /  \/ | | | .  . |
#|  __/  | | | |   | | | | |\/| |
#| |    _| |_| \__/\ \_/ / |  | |
#\_|    \___/ \____/\___/\_|  |_/
#                                
                                
# -----------
# -- Intel --
# -----------
vsync = true;

# -------------
# -- Backend --
# -------------

# -------------
# -- Shadows --
# -------------
shadow = true
shadow-exclude =  [
    "class_g = 'dzen'"                 
];

# shadow-radius=0
shadow-ignore-shaped = true

# -------------
# -- Opacity --
# -------------
detect-client-opacity = true
frame-opacity = 1.0

# -------------
# ---- Blur ---
# -------------
blur-background = false
blur-background-frame = false
blur-background-exclude = [
  "window_type = 'menu'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'tooltip'",
  "class_g = 'Alacritty'"
];

# -------------
# -- Fading ---
# -------------
fading = true
fade-delta = 3
fade-in-step = 0.05
fade-out-step = 0.03
no-fading-openclose = false

fade-exclude = [
    "class_g = 'Rofi'",
    "class_g = 'rofi -run'"
]

# ---------------------
# -- Rounded Corners --
# ---------------------
corner-radius = 0;
round-borders = 1;
rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'panel'",
    "window_type = 'popup_menu'"
    # "class_g *?= 'rofi'",
];

# -------------
# -- Dimming ---
# -------------
# Dim inactive windows. (0.0 - 1.0, defaults to 0).
inactive-dim = 0.00;
inactive-dim-exclude = [
    "class_g = 'Rofi'",
    "class_g = 'Firefox'",
    "class_g = 'firefox'",
    "class_g = 'Zathura'",
    "class_g = 'zathura'",
    "class_g = 'mpv'"
]

# -------------
# -- Windows ---
# -------------
wintypes:
{
  normal = { fade = false; shadow = true; }
  dock = { shadow = true; }
  menu = { shadow = false; opacity = 1.0; }
  popup_menu = { shadow = false; opacity = 1.0 }
  dropdown_menu = { shadow = false; }
  utility = { shadow = false; };
};

