# ________  ____   ___   __
#|_   _|  \/  | | | \ \ / /
#  | | | .  . | | | |\ V / 
#  | | | |\/| | | | |/   \ 
#  | | | |  | | |_| / /^\ \
#  \_/ \_|  |_/\___/\/   \/
#                          
# Prefix ,      -> Rename window
# Prefix +      -> Rename session
# Prefix w      -> Open session manager
# Prefix n,p    -> Hop between windows/tabs
# Prefix ()     -> Hop between sessions
# Prefix y      -> Enter copy mode
# (copy mode) y -> Copy/End copy mode
# (copy mode) <Enter> -> Copy/End copy mode

# ---------------------
# -- Terminal Colors --
# ---------------------
set-option -ga terminal-overrides ",xterm-256color:Tc"

# --------------
# -- Bindings --
# --------------
# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config
bind r source-file ~/.config/tmux/tmux.conf

# Vi-like Bindings
setw -g mode-keys vi

# Vi-like copy
unbind y
unbind p
unbind [
bind y copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# System Clipboard interaction
bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

# Mouse Scrolling
set -g mouse on

# Allows for faster key repetition
set -s escape-time 0

# Start window and pane numbering at 1, (0 is too hard to reach).
set -g base-index 1
set -g pane-base-index 1

# Kill Pane
unbind x
bind-key x kill-pane

# Set window split shortcuts
unbind '"'
unbind %
unbind v
unbind s
bind-key v split-window -h  # Vertical
bind-key s split-window     # Horizontal

# Switch panes using hjkl with Prefix
unbind h
unbind j
unbind k
unbind l

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Resize panes
unbind S-left
unbind S-down
unbind S-up
unbind S-right

bind -r -n S-down resize-pane -D    # (Resizes the current pane down)
bind -r -n S-up resize-pane -U      # (Resizes the current pane upward)
bind -r -n S-left resize-pane -L    # (Resizes the current pane left)
bind -r -n S-right resize-pane -R   # (Resizes the current pane right)

# Switching Tabs with no Prefix using Alt
unbind M-j
unbind M-k
bind -r -n M-j select-window -t :-
bind -r -n M-k select-window -t :+

# Switching between Sessions and Swapping Windows within Sessions
unbind (
unbind )
unbind M-l
unbind M-h
unbind M-L
unbind M-H
bind -r -n M-l swap-window -t +1 \; next-window
bind -r -n M-h swap-window -t -1 \; previous-window
bind -r -n M-L switch-client -n
bind -r -n M-H switch-client -p

# Layout Changes
unbind o
unbind p
unbind M-o
unbind M-p
bind-key -r -n M-o swap-pane -U
bind-key -r -n M-p swap-pane -D

# Status Bar - CURRENTLY ON
set -g status on

# Toggle Status Bar
unbind M-s
bind-key -n M-s set-option status

# -----------
# -- Theme --
# -----------

# Status Bar
set-option -g status-position bottom

set -g status-bg default
set -g status-fg '#ffffff'

set -g automatic-rename off


set -g window-status-format '#[fg=#'#7c818c'] #W '
set -g window-status-current-format '#[fg=#'#ffffff'] #W '

set -g status-right-style fg='#ffffff'
set -g status-right-length 40
set -g status-right 'Session: #S'
#set -g status-right '#(~/.config/tmux/scripts/sessions.sh)'
#set -g status-right '#(~/.config/tmux/scripts/git.sh #{pane_current_path})'

set -g status-left-style fg='#ffffff'
set -g status-left-length 40
set -g status-left ''

set -g status-justify centre

# Pane Borders
set-option -g pane-border-style fg='#7c818c' # Not Active Border
set-option -g pane-active-border-style fg='#7c818c' # Active Border

# Copy Mode Highlighting
set-window-option -g mode-style bg='#ffffff',fg='#263238'

# Message text
set-option -g message-style fg='#ffffff' 
