-- Scheme: Andromeda -- GENERATED by `base16 lua`; edit the .yaml source, not this.
return {
    base00 = "#262a33",
    base01 = "#2e323c",
    base02 = "#5a5c62",
    base03 = "#666666",
    base04 = "#b5b5a8",
    base05 = "#e5e5e5",
    base06 = "#ece7e7",
    base07 = "#f8f8f0",
    base08 = "#cd3131",
    base09 = "#f39c12",
    base0A = "#e5e512",
    base0B = "#05bc79",
    base0C = "#0fa8cd",
    base0D = "#2472c8",
    base0E = "#bc3fbc",
    base0F = "#ee5d43",
}
