-- Scheme: Duckbones -- GENERATED by `base16 lua`; edit the .yaml source, not this.
return {
    base00 = "#0e101a",
    base01 = "#202331",
    base02 = "#323549",
    base03 = "#444860",
    base04 = "#b3b692",
    base05 = "#ebefc0",
    base06 = "#f0f3d0",
    base07 = "#f5f7e0",
    base08 = "#e03600",
    base09 = "#f6a100",
    base0A = "#e39500",
    base0B = "#5dcd97",
    base0C = "#00a3cb",
    base0D = "#00a3cb",
    base0E = "#795ccc",
    base0F = "#8a5900",
}
