-- Scheme: Desert -- GENERATED by `base16 lua`; edit the .yaml source, not this.
return {
    base00 = "#333333",
    base01 = "#4d4d4d",
    base02 = "#626262",
    base03 = "#808080",
    base04 = "#b3b3b3",
    base05 = "#e6e6e6",
    base06 = "#f2f2f2",
    base07 = "#ffffff",
    base08 = "#ff5555",
    base09 = "#cd853f",
    base0A = "#f0e68c",
    base0B = "#98fb98",
    base0C = "#66cdaa",
    base0D = "#87ceff",
    base0E = "#ff55ff",
    base0F = "#a0522d",
}
