-- Scheme: Dark Pastel -- GENERATED by `base16 lua`; edit the .yaml source, not this.
return {
    base00 = "#000000",
    base01 = "#1c1c1c",
    base02 = "#393939",
    base03 = "#555555",
    base04 = "#888888",
    base05 = "#bbbbbb",
    base06 = "#dddddd",
    base07 = "#ffffff",
    base08 = "#ff5555",
    base09 = "#ffaa55",
    base0A = "#ffff55",
    base0B = "#55ff55",
    base0C = "#55ffff",
    base0D = "#5555ff",
    base0E = "#ff55ff",
    base0F = "#ff8855",
}
