-- Scheme: Datum Light -- GENERATED by `base16 lua`; edit the .yaml source, not this.
return {
    base00 = "#f1f6fd",
    base01 = "#e7ecf2",
    base02 = "#ced3d9",
    base03 = "#616a76",
    base04 = "#454c55",
    base05 = "#292e35",
    base06 = "#20242a",
    base07 = "#15181d",
    base08 = "#a44602",
    base09 = "#976700",
    base0A = "#756f1d",
    base0B = "#107c5a",
    base0C = "#0b7b80",
    base0D = "#0068a4",
    base0E = "#983472",
    base0F = "#976700",
}
