-- Scheme: Datum Dark -- GENERATED by `base16 lua`; edit the .yaml source, not this.
return {
    base00 = "#0f1318",
    base01 = "#1d2126",
    base02 = "#2b2f35",
    base03 = "#8f98a3",
    base04 = "#b5bcc5",
    base05 = "#dbe0e8",
    base06 = "#e4e9ef",
    base07 = "#eef2f7",
    base08 = "#ef844a",
    base09 = "#e6ac4c",
    base0A = "#d8cf58",
    base0B = "#51daa7",
    base0C = "#5ddae0",
    base0D = "#66b6f4",
    base0E = "#db78b1",
    base0F = "#e6ac4c",
}
