#!/bin/bash
#
# Exports for bash
export WM='herbstluftwm'
export VISUAL='vim'
export EDITOR="vim"
export GIT_EDITOR='vim'
export DIFFPROG='vim'
export PAGER='less'
export READER='zathura'
export BROWSER='firefox'

export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_VIDEOS_DIR="$HOME/Videos"
export XDG_DATA_HOME="$HOME/.local/"
export XDG_CACHE_HOME="$HOME/.cache/"
export XDG_CONFIG_HOME="$HOME/.config/"

export TERM='xterm-256color'
export VIMINIT='source $CUSTOM_VIMRC'
export CUSTOM_VIMRC='/home/duclos/.config/vim/vimrc'
export LYNX_LSS='/home/duclos/.config/lynx/lynx.lss'
export LYNX_CFG='/home/duclos/.config/lynx/lynx.cfg'
export PYLINTHOME="${XDG_DATA_HOME}/pylint"
export GIT_CONFIG='/home/duclos/.config/git/config'
export GTK2_RC_FILES='/home/duclos/.config/gtk-2.0/gtkrc-2.0'
export QT_QPA_PLATFORMTHEME='qt5ct'
export QT_STYLE_OVERRIDE='kvantum-dark'
export IPYTHONDIR='/home/duclos/.config/ipython/'
export CARGO_HOME='/home/duclos/.cache/cargo/'
export GNUPGHOME='/home/duclos/.gnupg'
export WEECHAT_HOME='/home/duclos/.config/weechat'
export INPUTRC='/home/duclos/.config/bash/inputrc'
export XINITRC='/home/duclos/.config/X11/xinitrc'
export MPD_HOST="$HOME/.config/mpd/socket"
export VIRTUAL_ENV_DISABLE_PROMPT=1
export LESSHISTFILE=-
export FZF_ALT_C_COMMAND="command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune -o -type d -not -path '*VMs*' -not -path '*Music*' -not -path '*/\.*' -print 2> /dev/null | cut -b3-"
# export FZF_DEFAULT_COMMAND='find --type f -not -path "*VMs*" -not -path "*Music*" -not -path "*/\.*"'

export WINIT_HIDPI_FACTOR=1              # Necessary for Alacritty
export WINIT_X11_SCALE_FACTOR=1          # Necessary for Alacritty
export _JAVA_AWT_WM_NONREPARENTING=1     # Necessary for MATLAB and Xilinx Vivado
