#!/bin/bash
#
# Main function that calls on all modules necessary for the bash prompt

## Prompt Info
    # Colors
    #
    # Black   30
    # Red     31
    # Green   32
    # Yellow  33
    # Blue    34
    # Purple  35
    # Cyan    36
    # White   37
    #
    # Attributes
    # 
    # Normal      0
    # Bold/Light  1
    # Dim Text    2
    # Underlined  4
    # Blinking    5
    # Reversed    7
    # Hidden      8
    #
    # Backgrounds
    #
    # Black      40
    # Red        41
    # Green      42
    # Yellow     43
    # Blue       44
    # Purple     45
    # Cyan       46
    # White      47

black='\[\033[00;30m\]'
red='\[\033[00;31m\]'
green='\[\033[00;32m\]'
yellow='\[\033[00;33m\]'
blue='\[\033[00;34m\]'
purple='\[\033[00;35m\]'
cyan='\[\033[00;35m\]'
white='\[\033[00;37m\]'

b_black='\[\033[01;30m\]'
b_red='\[\033[01;31m\]'
b_green='\[\033[01;32m\]'
b_yellow='\[\033[01;33m\]'
b_blue='\[\033[01;34m\]'
b_purple='\[\033[01;35m\]'
b_cyan='\[\033[01;35m\]'
b_white='\[\033[01;37m\]'

cb_git_prefix() {
  local git_flag=$(git rev-parse --is-inside-work-tree 2>/dev/null | grep true)
  local prefix=" on "
  
  if [[ -n "$git_flag" ]]; then
    echo -e "$prefix"
  else
    echo -n ""
  fi
}

cb_git_wrap_1() {
  local git_flag=$(git rev-parse --is-inside-work-tree 2>/dev/null | grep true)
  local prefix="git:("
  
  if [[ -n "$git_flag" ]]; then
    echo -e "$prefix"
  else
    echo -n ""
  fi
}

cb_git_wrap_2() {
  local git_flag=$(git rev-parse --is-inside-work-tree 2>/dev/null | grep true)
  local prefix=")"
  
  if [[ -n "$git_flag" ]]; then
    echo -e "$prefix"
  else
    echo -n ""
  fi
}

cb_git_prompt() {
  . $HOME/.config/bash/git/bash_git_status.sh

  local git_flag=$(git rev-parse --is-inside-work-tree 2>/dev/null | grep true)
  # local git_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n')
  # echo -e "$git_branch"
  
  if [[ -n "$git_flag" ]]; then
    git_prompt="$(__git_ps1 "%s")"
    git_prompt=$(echo "$git_prompt" | sed 's/\[//g')
    git_prompt=$(echo "$git_prompt" | sed 's/\]//g')
    echo -e "$git_prompt"
  else
    echo -n ""
  fi
}

cb_pyenv_prefix() {
  if [[ -n "$VIRTUAL_ENV" ]]; then
    local prefix=" via "
    echo -e "$prefix"
  else
    echo -n ""
  fi
}

cb_pyenv_prompt() {
  if [[ -n "$VIRTUAL_ENV" ]]; then
    local venv=$(python --version | cut -d ' ' -f2)
    local venv=$(printf "%s" "venv $venv")
    echo -e "$venv"
  else
    echo -n ""
  fi
}

bash_prompt() {
  export GIT_PS1_SHOWUPSTREAM=1
  export GIT_PS1_SHOWDIRTYSTATE=1
  export GIT_PS1_SHOWSTASHSTATE=1
  export GIT_PS1_UNTRACKEDFILES=1
  export GIT_PS1_COMPRESSPARSESTATE=1

  unset GIT_PS1_HIDE_IF_PWD_IGNORED

  local RIGHT='\033[500C'

  # PS1='\[\033[01;32m\] ➜ '
  # PS1='\[\033[01;32m\] > '
  PS1='\[\033[01;32m\]\W'
  PS1+='\[\033[01;37m\]$(cb_git_prefix)'
  PS1+='\[\033[01;35m\]$(cb_git_wrap_1)'
  PS1+='\[\033[01;31m\]$(cb_git_prompt)'
  PS1+='\[\033[01;35m\]$(cb_git_wrap_2)'
  # PS1+='\[\033[01;33m\] ✗ '
  PS1+='\[\033[00;37m\] $ '
  PS1+="\[\033[0m\]"

  export PS1
}

# vim: ft=bash
